travis:
  secure:
    BINSTAR_TOKEN: aa5lo8pFAs2eR6eCTpqquSyxcaBdUIBJKBvsU59k8DEnUAz3LKZS8vTu0PMuwuYDWe0N8H5FzWs2Rb4/sR4su3zwvFUullq0N8p75Akq6Fx5pgWqBCWz7WuPtHYFuXqmvEePH+f0MysJB0XIyLIsSaCQgFNg3nxj5QUYHlOTE/Rm0c/BoBmihgwe0HZo9zeRXRMFGJb0ks5id7r/Cy6WbCK+W1368N7pgyaaCBPtBBL0zf3qfJcGLS3jVCWcolxzXE1gGZIbGpbjzFVpT8zmlM7c6XIeUclQZFexpqGlzhuimTRcylKV7Y8eKJ50JUFnq67ism56SW7GtN3F/yif/LgDqzkktQW7eXMcfnhlknbQ7CtC3YLRTrIPDrDHDWn8keOJkkX+2gR2MTMsSnhJ/Lwzm6tbvOhNRD8yCEePDWwlSmHN7cIrXcZVOj9+OXmaElNVDRo1f+JiOIiB2is7emw6aow7FvLmbgx85Y9SFjjTkKpw8TyfnE5/d4jHGYTDCofmtrotQRrwjLVBc54QqFiNzQsy4TNdO9o+eB0lekZukB2eJteSIxhZXt9QukQ1nCIiXABa5vXsgNXMUI3wBj6zqDLf1cPV1LZcCnhm9TsBE7rDkGm81rm/qTO8leRQHPlwDXgYw6r0N5YkAQKEUbp15U1oX/PXCpM1vC9xMWI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
