travis:
  secure:
    BINSTAR_TOKEN: lpOPJAi0C+eocK+V5bSbXkpkQ5tlh39g6fZP+OV3+VpQKM0d/LLWmPxwb6l1XNrwbQrnl6CHpBJh69hxfkyfEkwoD/iMZtEhMZHKZPlfScercjbKV3UhGU5tu5LQWb9wjms9mlz639nJb1y24p9+a9lTGolUdomz1ovh1JOvIHZbB9APKoULJVqE+fmGlGAcVhgwG3NEpVzQfWboUyDIZ4y/spWY8ZAywXJKscBNSG15NZjsGisF2kbd+cxZb7mjsM/mHexU4B1hejf/4B4F5SIcTB5u0+EHycv04q9+GZw1hctC6IAW7yhTiaxhJEuqO1SulFxygfUD2PCWnw5PPjnjmjtva+yWNw/kRA8QI+KlLv/jcXIXBkjz+uRSg1DhMRBQ1jv/ZOWQL5RhyBMco4b5xXdBLoFyJ/3UopmyuQqZJZCXXA+BbFh3bdfrFAC+oPRrjpMqW9j49nrpU+spBGYAmbhaCCDMAO3tOcLoF/Fr3pV73exC8joT33n5ShwEwGvktuW6ncFXmR8BKRyXY8YIwwnVY//4GKnJY8t9cDMjO9xyj3zJt1m4mfM7+iYQPANfMDuAfNF7lGXtLhtDrnrN6+TmKeyP4wsvGTe8vUwynV2liuhK+YNoSxPC+HE8/AviqqtiaOrKgLnrkXJ8AOBh76qXD+NmnLCrTbtLkEw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
